UserAuthProject3/UserAuthProject3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userapp.urls')),
]

UserAuthProject3/userapp/urls.py
#from django.conf.urls import urls
from django.urls import path
from . import views

app_name = 'userapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register')
]

UserAuthProject3/userapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    facebook_id = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)


    def __str__(self):
        return self.user.username

UserAuthProject3/userapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('facebook_id', 'profile_pic')

UserAuthProject3/userapp/views.py
from django.shortcuts import render
from .forms import UserForm,UserInfoForm
#from .forms import forms


# Create your views here.
def index(request):
    dict = {}
    return render(request, 'login_app/index.html', context=dict)


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user

            if 'profile_pic' in request.FILES:        #FOR ALL FILES
                user_info.profile_pic = request.FILES['profile_pic']
            user_info.save()

            registered = True

    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()


    user_form = UserForm()
    user_info_form = UserInfoForm()
    diction = {'user_form': user_form, 'user_info_form': user_info_form, 'registeres':registered}
    return render(request, 'login_app/register.html', context=diction)

UserAuthProject3/templates/login_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{{ title }}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'userapp:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'userapp:register' %}">Register</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<div class="container" style="padding-top:20px">
    {% block body_block%}

    {% endblock %}
</div>







    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

UserAuthProject3/templates/login_app/index.html
{% extends 'login_app/base.html' %}


{% block body_block%}
    <h1>I am Index Page </h1>
{% endblock %}

UserAuthProject3/templates/login_app/register.html
{% extends 'login_app/base.html' %}
{% load static %}

{% block body_block %}
{% if registered %}
<div class="alert alert-success">Congratulations ! Registration Successfull</div>
{% else %}

    <h5>Register Form</h5>
    <form enctype="multipart/form-data",method = "POST">
        {{ user_form.as_p}}
        {{ user_info_form.as_p }}
        {% csrf_token %}
        <input type="submit", name="submit", value="Register">
    </form>
{% endif %}
{% endblock %}