Projects1/Projects1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects_apps.urls')),
]

Projects1/projects_apps/urls.py
#from django.conf.urls import url
from django.urls import path
from . import views

app_name= "first_app"


urlpatterns = [
    path('', views.index, name='index'),
    path('form/', views.form, name='form'),
    #path('test/', views.contact, name = 'contact'),
]

Projects1/projects_apps/models.py
from django.db import models

class Musician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)


    def __str__(self):
        return self.first_name + " " + self.last_name



class Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE )
    name = models.CharField(max_length=100 )
    release_date = models.DateField()
    rating = (
        (1, "Worst"),
        (2, "Bad"),
        (3, "Good"),
    )
    num_stars = models.IntegerField(choices=rating)





    def __str__(self):
        return self.name + ", Rating: " + str(self.num_stars)

Projects1/projects_apps/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import forms


# Create your views here.

def index(request):
    diction = {'sample_text': "Sample text"}
    return render(request, 'projects_apps/index.html')

def form(request):
    return render(request, 'projects_apps/form.html')

Projects1/templates/projects_apps/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'first_app:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:form' %}">Form</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<div class="container">
    {% block body_block%}

    {% endblock %}
</div>







    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

Projects1/templates/projects_apps/form.html
<!DOCTYPE html>
{% extends "projects_apps/base.html" %}

{% block body_block %}
    <h1>I am Form page !</h1>
{% endblock %}

Projects1/templates/projects_apps/index.html
<!DOCTYPE html>

{% extends "projects_apps/base.html" %}
{% load static %}


{% block body_block %}
    <h1>I am index page !</h1>
    <h3> {{ sample_text  }}</h3>
{% endblock %}