project2/myapp/urls.py
#from django.conf.urls import url
from django.urls import path
from . import views

app_name= "myapp"


urlpatterns = [
    path('', views.index, name='index'),
    path('add_album/', views.album_form, name='album_form'),
    path('add_musician/', views.musician_form, name='musician_form'),
    path('album/list/<int:artist_id>/', views.album_list, name='album_list'),
    path('edit_artist/<int:artist_id>/', views.edit_artist, name='edit_artist'),
    path('edit_album/<int:album_id>/', views.edit_album, name='edit_album'),
    #path('test/', views.contact, name = 'contact'),
]

project2/project2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

project2/myapp/models.py
from django.db import models

class Musician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)


    def __str__(self):
        return self.first_name + " " + self.last_name



class Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE )
    name = models.CharField(max_length=100 )
    release_date = models.DateField()
    rating = (
        (1, "Worst"),
        (2, "Bad"),
        (3, "Good"),
    )

    num_stars = models.IntegerField(choices=rating)





    def __str__(self):
        return self.name + ", Rating: " + str(self.num_stars)

project2/myapp/forms.py
from django import forms
from . import models

class MusicianForm(forms.ModelForm):
    class Meta:
        model = models.Musician
        fields = "__all__"


class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = models.Album
        fields = "__all__"

project2/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import forms
from .models import Musician, Album
from django.db.models import Avg, Min, Max


# Create your views here.

def index(request):
    musician_list = Musician.objects.order_by('first_name')
    diction = {'title': "Home Page ", 'musician_list': musician_list}
    return render(request, 'projects_apps/index.html', context=diction)


def album_list(request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    album_list = Album.objects.filter(artist=artist_id).order_by('name', 'release_date')
    artist_rating = Album.objects.filter(artist=artist_id).aggregate(Avg('num_stars'))

    diction = {'title': "List of Album", 'artist_info': artist_info, 'album_list': album_list,
               'artist_rating': artist_rating}
    return render(request, 'projects_apps/album_list.html', context=diction)


def musician_form(request):
    form = forms.MusicianForm()
    if request.method == 'POST':
        form = forms.MusicianForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'title': "Add Musician", 'musician_form': form}
    return render(request, 'projects_apps/musician_form.html', context=diction)


def album_form(request):
    form = forms.AlbumForm

    if request.method == 'POST':
        form = forms.AlbumForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'title': "Add Album", 'album_form': form}
    return render(request, 'projects_apps/album_form.html', context=diction)


def edit_artist(request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id) #SHOWING VALUE IN INPUT BOX FOR EDIT
    form = forms.MusicianForm(instance=artist_info)

    if request.method=='POST':
        form=forms.MusicianForm(request.POST, instance=artist_info)

        if form.is_valid():
            form.save(commit=True)
            return album_list(request, artist_id)


    diction = {'edit_form': form}
    return render(request, 'projects_apps/edit_artist.html', context=diction)


def edit_album(request, album_id):
    album_info = Album.objects.get(pk=1)
    form = forms.AlbumForm(instance=album_info)
    diction = {}
    if request.method=='POST':
        form = forms.AlbumForm(request.POST, instance=album_info)

        if form.is_valid():
            form.save(commit=True)
            diction.update({'success-text': 'Successfully updated'})
    diction.update({'edit_form': form})
    return render(request, 'projects_apps/edit_album.html',context=diction)

project2/templates/projects_apps/album_form.html
<!DOCTYPE html>

{% extends "projects_apps/base.html" %}
{% load static %}


{% block body_block %}
    <h1>I am Album Form page !</h1>
<form method="POST">
    {{ album_form.as_p }}
    {% csrf_token%}
    <input class="btn btn-primary btn-sm" type="submit" name="submit", value="Add">
</form>
{% endblock %}

project2/templates/projects_apps/album_list.html
<!DOCTYPE html>

{% extends "projects_apps/base.html" %}
{% load static %}


{% block body_block %}
    <h4>Artist Name: {{ artist_info.first_name }} {{ artist_info.last_name }}</h4>
    <h4>Artist Instrument: {{ artist_info.instrument }}</h4>
    <h4>Artist Rating: {{ artist_rating.num_stars__avg }}</h4>

    <a href="{% url 'myapp:edit_artist' artist_id=artist_info.id %}", class="btn btn-info btn-sm">Edit</a>
    <h5>List of Album...... </h5>
    <table class="table table-border">
        <tr>
            <th>Album Name</th>
            <th>Release date</th>
            <th>Rating</th>
        </tr>
        {% for album in album_list %}
        <tr>
            <td><a href="{% url 'myapp:edit_album' album_id=album.id %}">{{ album.name }}</a></td>
            <td>{{album.release_date |date:"M D, Y" }}</td>
            <td>{{ album.num_stars }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

project2/templates/projects_apps/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{{ title }}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'myapp:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:musician_form' %}">Add Musician</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'myapp:album_form' %}">Add Album</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<div class="container">
    {% block body_block%}

    {% endblock %}
</div>







    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

project2/templates/projects_apps/edit_album.html
<!DOCTYPE html>

{% extends "projects_apps/base.html" %}
{% load static %}

{% block body_block %}
<h4>Edit Album </h4>
{% if success_text %}
<div class="alert alert-success"> {{ success_text }} </div>

{% endif %}

<form method="POST">
    {{ edit_form.as_p }}
    {% csrf_token %}
   <input CLASS="btn btn-success btn-sm" type="submit"  name="submit" value="Update">
</form>


{% endblock %}

project2/templates/projects_apps/edit_artist.html
<!DOCTYPE html>

{% extends "projects_apps/base.html" %}
{% load static %}


{% block body_block %}
<h4>Edit Artist </h4>
    <form method="POST">
        {{ edit_form.as_p }}
        {% csrf_token %}
       <a href="{% url 'myapp:edit_album' %}"> <input class="btn btn-success btn-sm" type="submit", name="submit", value="Update"></a>
    </form>

{% endblock %}

project2/templates/projects_apps/form.html
<!DOCTYPE html>
{% extends "projects_apps/base.html" %}

{% block body_block %}
    <h1>I am Form page !</h1>
{% endblock %}

project2/templates/projects_apps/index.html
<!DOCTYPE html>

{% extends "projects_apps/base.html" %}
{% load static %}


{% block body_block %}
<h1>I am index page !</h1>
<h3>List of Musicians: </h3>
<ul>
    {% if musician_list %}
    {% for musician in musician_list %}
    <li><a href="{% url 'myapp:album_list' artist_id=musician.id %}"> {{musician.first_name}} {{ musician.last_name }}</a></li>
    {% endfor %}
    {% else%}
    <h5>No Musician in the List </h5>
    {% endif %}
</ul>
{% endblock %}

project2/templates/projects_apps/musician_form.html
<!DOCTYPE html>

{% extends "projects_apps/base.html" %}
{% load static %}


{% block body_block %}
    <h1>I am Musician page !</h1>
<form method="POST">
    {{ musician_form.as_p }}
    {% csrf_token%}
    <input class="btn btn-primary btn-sm" type="submit" name="submit", value="Add">
</form>
{% endblock %}